### ISSUE TITLE
Modify the background image

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#1]
Replace the background image with pclub logo

**Comment by ArihantJain456** [comment]
hey , can I do this change

**Comment by ashwani99** [comment]
@divyam3897 Does this look good?

**Comment by deveshd2k** [comment]
use this image for high resolution:
![newlogo](https://user-images.githubusercontent.com/31280226/31065866-36e973a2-a766-11e7-81ae-f2eb57616ef3.jpg)

**Comment by ashwani99** [comment]
@deveshd2k Don't you think it is still too small? Stretching this to fit screen would blur the image.

**Comment by divyam3897** [comment]
@ashwani99 can you make a .svg similar to the same and make a div for it below the navbar and not use it as background image?

**Comment by ashwani99** [comment]
@divyam3897 Sorry, I'm not good with logo designing stuff. As a suggestion, I think there has to be much more black background around the logo so that it will prevent the actual logo becoming too large when we put it as a background. What do you think?

**Comment by deveshd2k** [comment]
i tried making svg but only black and white color is there after conversion. No green color and background
 effect is also gone.

**Comment by deveshd2k** [comment]
can you please get me the actual resolution in pixels you want for image??

**Comment by ashwani99** [comment]
@deveshd2k I am not too sure of this because depending on the screen size the background will become bad. Maybe a 1280x1024 would be fine. Also, is it really necessary to put the logo as background?

**Comment by divyam3897** [comment]
It won't be the background any more , see the  issue of adding about us, it would just be a section of some finite height below the navbar

**Comment by divyam3897** [comment]
It has a seperate issue now https://github.com/pclubuiet/website/issues/77 So closing this duplicate one which is not required.
