### ISSUE TITLE
Add models

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#115]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request
- [ ] support request

Add models for resources.  There should be a main resource model where there is image, title of resource example C++ and image and a relation to another model which will contain all it's resources.

**Comment by AndrewTelleria** [comment]
Hello, I would like to take this.

**Comment by divyam3897** [comment]
@AndrewTelleria Hi. sure go for it. Read our README for the development workflow and best practices.

**Comment by gurpreetsingh00885** [comment]
@divyam3897 is an image even required? All the images will have to be consistent then. Why go through all the trouble?

**Comment by gurpreetsingh00885** [comment]
completed via pr#140
