### ISSUE TITLE
Add login

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#126]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ X] feature request
- [ ] support request

**Expected behavior:**
Add login for a user

**Comment by Nepaltechguy2** [comment]
What language would you like this login to be created in?

**Comment by divyam3897** [comment]
@Nepaltechguy2 we are using the django framework which is a python framework

**Comment by sagar-kalra** [comment]
Claiming
