### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#135]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [X ] support request

Update the README.md with instructions on setting the website with docker container, refer the Docker file and docker-compose.yml

**Comment by blackpioter** [comment]
I'll take it if you don't object.

**Comment by divyam3897** [comment]
Sure, go for it :)

**Comment by blackpioter** [comment]
@divyam3897 ok, I've described basic requirements and steps for running with Docker Compose. If you need something more let me know.
