### ISSUE TITLE
Problem in migration

### ISSUE THREAD

**Issue by Mahirgupta** [pclubuiet/website#142]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ x ] feature request
- [ x ] support request

**Current behavior:**

When the "Python3 manage.py migrate" command is run in the terminal, the following error shows up:
"""
File "/root/Desktop/env/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "pclubuietdb" to address: Name or service not known
"""

**Expected behavior:**

It should migrate the required apps and run the application.

**Comment by gurpreetsingh00885** [comment]
Its a problem with the instructions in the README. It doesn't list the steps to setting up a postgresql database to be used by the website.

**Comment by Mahirgupta** [comment]
so what should be done regarding this as I don't know anything about this. If i knew then I would have solved the issue and started working on the site. And because of this I am not able to work on the site.

**Comment by gurpreetsingh00885** [comment]
fixed via #146
