### ISSUE TITLE
Clean code in base.html

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#17]
Currently all the html code is in one file. Add the base.html with the head, footer and block body and insert the body code in block body

**Comment by mani87** [comment]
What exactly is the rquirenment can you tell me please? :)

**Comment by divyam3897** [comment]
@mani87 when we have multiple html files we don't want to add the code for head, navbar, footer again and again. We use refactored code i.e avoiding writing same piece of code again and again. So a base.html is to be made adding the code that is used again and again and then it is just to be included in home.html

**Comment by mani87** [comment]
Okay :).. Thanks!
