### ISSUE TITLE
Add contact us 

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#28]
Add links to 
Facebook page: bit.ly/pclubfb
slack: tinyurl.com/pclubslack
mail: pclubuiet@gmail.com

**Comment by shovanch** [comment]
Working on it

**Comment by divyam3897** [comment]
can you assign the issue to yourself?

**Comment by shovanch** [comment]
I can't. It needs write access. Only possible from your end.

**Comment by divyam3897** [comment]
It has been added in https://github.com/pclubuiet/website/commit/44e7fdc0bfc83b6f32e9c013a08dda949fcf2f9a
