### ISSUE TITLE
Add about us

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#42]
Change the background to a div for top, add an about us section below it with:
"Programming club is one of the biggest clubs of Panjab University. We aim and create a platform which allows students to gain assistance and mentorship to enhance their ability. Our aim is to propagate the enthusiasm for programming in the institute. We believe that every student should have an opportunity to learn how to code and we help them develop that passion for it."

**Comment by jimjja** [comment]
I can work on this

**Comment by surana-mudit** [comment]
Hi!
@divyam3897 I would like to work on this issue but I am not able to understand properly where do I need to put the about us section. So could you please explain it to me?

**Comment by divyam3897** [comment]
@surana-mudit for now there is a background image, reduce it to a div (just below the navbar) and then a about us section below that with the above mentioned text.
