### ISSUE TITLE
Add forking step to README.md

### ISSUE THREAD

**Issue by gurpreetsingh00885** [pclubuiet/website#5]
As of now, the README.md does not have a step that informs newcomers to fork the repo. 
It needs to be added.

**Comment by colelabar** [comment]
I'm a relatively new developer, and haven't contributed to open-source yet, but this seems pretty straightforward! I should just add the step in the beginning?

**Comment by rahul577** [comment]
if we add the forking step then should we change the cloning step too because now it is cloning the original repository ?

**Comment by divyam3897** [comment]
yes, that's all you need to do @colelabar 
that's added as a seperate issue @rahul577

**Comment by divyam3897** [comment]
Fixed in https://github.com/pclubuiet/website/commit/4d5cab1dd1daa5b04d87b0672d5ad8e483778cad
