### ISSUE TITLE
Make "/" redirect to "/home"

### ISSUE THREAD

**Issue by gurpreetsingh00885** [pclubuiet/website#66]
Currently, http://pclubuiet.herokuapp.com/ leads to an error as no view responds to this request. 
The home page is at http://pclubuiet.herokuapp.com/home

Just make the former redirect to the latter.

**Comment by naman** [comment]
Please check https://github.com/pclubuiet/website/pull/68.

**Comment by AmanNim98** [comment]
Can i work on this issue sir?

**Comment by sammysgame** [comment]
Would like to work on this issue... ;)

**Comment by jkingz** [comment]
Fix it on PR #75

**Comment by 01samiksha** [comment]
Can I take up this issue?

**Comment by sagar-kalra** [comment]
Yes, you can, since no is assigned for this issue. @01samiksha

**Comment by divyam3897** [comment]
@01samiksha there are already PRs for this also, so we would suggest pick some other issue, thank you

**Comment by harshitjindal** [comment]
This issue has been solved. It can be closed now
