### ISSUE TITLE
README.md: Add a step to use a virtual environment.

### ISSUE THREAD

**Issue by gurpreetsingh00885** [pclubuiet/website#7]
This would be the ideal way.

**Comment by maykillmore** [comment]
I would like to give this a try.

**Comment by brianmituka** [comment]
is this issue fixed already?

**Comment by ashwani99** [comment]
@gurpreetsingh00885 I have added the changes. Can you please revirew it?

**Comment by divyam3897** [comment]
Fixed in https://github.com/pclubuiet/website/commit/4d5cab1dd1daa5b04d87b0672d5ad8e483778cad
