### ISSUE TITLE
Add a page for 404

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#73]
add a page for 404

**Comment by harshitjindal** [comment]
I can take this

**Comment by abdullah-K** [comment]
I can make one for you, too.
Would you mind taking a look at my 404 page and see if you like it: [http://khanabdullah.com/404](http://khanabdullah.com/404).
If you like it, I'll make one for you!

**Comment by divyam3897** [comment]
sure, feel free to make one :)

**Comment by abdullah-K** [comment]
@divyam3897  should I make it in the root directory of the project or in the "templates" folder?

**Comment by divyam3897** [comment]
@abdullah-K in the templates directory, please. Read our README which explains how to contribute 🚀
