### ISSUE TITLE
Better management of staticfiles and templates

### ISSUE THREAD

**Issue by gurpreetsingh00885** [pclubuiet/website#9]
@divyam3897 

I'd suggest something like a global static root, templates and staticfiles folder.
templates and staticfiles folders may have folders by the name of the app which would contain the templates or staticfiles related to the app.

See https://docs.djangoproject.com/en/1.10/howto/static-files/ and https://stackoverflow.com/questions/7192367/managing-static-files-for-multiple-apps-in-django

Would prevent issues when we need to use some staticfiles or templates globally.

**Comment by divyam3897** [comment]
@gurpreetsingh00885 I would go with the same, I would also prefer seperate urls for seperate apps.

**Comment by sagar-kalra** [comment]
Please review my PR https://github.com/pclubuiet/website/pull/40 .

**Comment by sagar-kalra** [comment]
https://github.com/pclubuiet/website/pull/57 Please review this,
