### ISSUE TITLE
Make navbar responsive

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#90]
Make the navbar responsive -> Collapse the navbar and add a button for it in small screen sizes.

**Comment by berviantoleo** [comment]
May I take this?

**Comment by divyam3897** [comment]
@berviantoleo there is already a PR for the same https://github.com/pclubuiet/website/pull/92 Can you pick another issue?

**Comment by berviantoleo** [comment]
Oh, I missed that because no reference to this issue. Okay. I will look another issue.
