### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by abdullah-K** [pclubuiet/website#94]
The following error is present in both the, home and resources view:
![github-issue-1](https://user-images.githubusercontent.com/21252681/31188887-bf5bcf9e-a8f3-11e7-8713-3c56e9c46930.PNG)

**Comment by divyam3897** [comment]
@abdullah-K I am not able to reproduce this one, can you make sure that you haven't removed it?

**Comment by abdullah-K** [comment]
@divyam3897 Aah! I'm sorry, I forgot to pull the latest commits to my fork. My bad, haha
