### ISSUE TITLE
Dockerize the website.

### ISSUE THREAD

**Issue by divyam3897** [pclubuiet/website#96]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x ] feature request
- [ ] support request

**Current behavior:**
Currently we need to setup the complete dev environment.

**Expected behavior:**
Add an alternative of docker container to make things easier.

**Comment by zorexsalvo** [comment]
Hi @divyam3897, is there already someone working on this enhancement?

**Comment by divyam3897** [comment]
no, @zorexsalvo feel free to work on it, just let us know if you will so that we can save others efforts :)

**Comment by zorexsalvo** [comment]
Yes I'm happy to take it! Will make pull request later or tomorrow.

**Comment by vladcalin** [comment]
@divyam3897  Please update the assignees so that other people can see that somebody is working on this without reading through all the comments.

**Comment by divyam3897** [comment]
@vladcalin we would be happy to do that but for that one needs to be a part of the organization. We would be happy for suggestions to do it without it if there is any, thanks.
